refactor(errors): Wrap Errors in TableError(BaseModel)
Refactored error types to have a common parent error type (`TableError`)
to address the mypy error on Windows. Initially, NamedTuple classes
were considered, but they undermined inheritance benefits and introduced
additional issues. Therefore, `pydantic.BaseModel` was used for the
following advantages:

- Provides serialization, eliminating the need for `error_to_dict()`.
- Enforces the use of named arguments, reducing potential errors when refactoring argument order.
- Fixes the mypy issue with missing type information.

src\senfd\errors.py:17: error: Invalid type alias: expression is not a valid type  [valid-type]
src\senfd\errors.py:17: error: Unsupported left operand type for | ("type[TableOfFiguresError]")  [operator]
src\senfd\errors.py:25: error: Variable "senfd.errors.TableError" is not valid as a type  [valid-type]
src\senfd\errors.py:25: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases
src\senfd\errors.py:26: error: TableError? has no attribute "_asdict"  [attr-defined]
Found 4 errors in 1 file (checked 18 source files)

Signed-off-by: Simon A. F. Lund <os@safl.dk>